# Generated by Django 5.1.1 on 2024-10-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('main_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True)),
                ('seance', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.questions')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.courses')),
            ],
            options={
                'db_table': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.tests'),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('data_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.courses')),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Userescoursesrel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.courses')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.users')),
            ],
            options={
                'db_table': 'UseresCoursesRel',
            },
        ),
        migrations.CreateModel(
            name='Testresults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('try_numb', models.SmallIntegerField(blank=True, null=True)),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.tests')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.users')),
            ],
            options={
                'db_table': 'TestResults',
            },
        ),
        migrations.CreateModel(
            name='Readtopics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.topics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courseapp.users')),
            ],
            options={
                'db_table': 'ReadTopics',
            },
        ),
    ]
